# action.yml
name: 'INSPECTA-Codebuild-CI-Action'
description: 'INSPECTA CI action to generate code from a SySML (v2) model'
inputs:
  sourcepath:
    description: 'Path to top level Makefile (expects path string).'
    required: false
    default: 'system/hamr/microkit'
  environment-variable:
    description: 'JSON-formatted dictionary of environment variables to pass to the make system.'
    required: '{}'
  report-filename:
    description: 'The name of the file into which to write the JSON-formatted code generation analysis report.'
    required: 'false'
    default: 'codebuild-report.json'
outputs:
  timestamp:
    description: 'The date/time that the code generation was completed'
  status:
    description: 'Summary of code generation status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sourcepath }}
    - ${{ inputs.environment-variables }}
    - ${{ inputs.report-filename }}
